### ISSUE TITLE
Problem with Parent Category

### ISSUE THREAD

**Issue by emanoj1** [yclas/documentation#359]
When creating Parent Category and Child Category, the Parent Category need to act as a label only for the set of Child Categories. It should neither be clickable nor allow users to post ads within it. Users can post only under Child categories. Do you know if there is a fix for this anomaly? This was noticed on Yclas version 3.4.0

![screen shot 2018-03-11 at 4 51 50 pm](https://user-images.githubusercontent.com/37259245/37250257-a8702412-254c-11e8-8b08-00998fc7cde9.png)
![screen shot 2018-03-11 at 4 52 15 pm](https://user-images.githubusercontent.com/37259245/37250258-a92b9b16-254c-11e8-82ba-e3080f351261.png)

Thank you for your time and looking forward to hearing from you.

**Comment by neo22s** [comment]
Hello,

You are posting a support question on the documentations. Please this is for the docs. use our support at yclas.com it is explained.

regards

**Comment by emanoj1** [comment]
Hi Chema,

My deep apologies :( It was my first time using Github. I decided to use it
because the link was there on your Yclas documentation. I clicked it and
saw issues being raised and hence decided to do the same. Won't do it again.

Cheers,
Mventures
