### ISSUE TITLE
Upload ads not working

### ISSUE THREAD

**Issue by irfankhan04** [yclas/documentation#384]
Hi,
I am trying to upload my ads to Yclas website and every time getting the error invalid character.
Please suggest.
Please see the attached.
![capture](https://user-images.githubusercontent.com/35433907/45929968-7228ca00-bf1e-11e8-8131-026e9192b545.PNG)

Any help would be appreciated.

Regards,
Irfan
![capture](https://user-images.githubusercontent.com/35433907/45929941-2118d600-bf1e-11e8-9f19-85675d8cb496.PNG)

**Comment by neo22s** [comment]
Hello,

This is not a support area. Please use the correct area. 

Import of ads works perfectly.

Thanks.
