### ISSUE TITLE
canonical tag 

### ISSUE THREAD

**Issue by AdsKhan** [yclas/documentation#386]
We using ycals I need to  ad proper canonical tag  For all my canonical urls for site pages, I dnt know Which code i need to use Currently i Try to this Code 
`**<link rel="canonical" href="<?=Route::url('default')?>" />**
``<link rel="canonical" href="https://www.adskhan.com/" />
`But this code not taken for whole website Pleas help me
 Thanks

**Comment by neo22s** [comment]
Hello,

This is github, not a support center, please for support use the proper channel. Either open a support ticket or write to us to info@yclas.com.

thanks.

**Comment by AdsKhan** [comment]
ok Thanks
