### ISSUE TITLE
Photo upload does not work

### ISSUE THREAD

**Issue by rececehu** [yclas/documentation#387]
Hello!
![2019-01-05 1](https://user-images.githubusercontent.com/46401054/50726247-c856fd00-110a-11e9-9dc1-962e8a0d7a53.png)
![2019-01-05 2](https://user-images.githubusercontent.com/46401054/50726248-c856fd00-110a-11e9-9deb-fdb1a6ebcc76.png)
![2019-01-05 3](https://user-images.githubusercontent.com/46401054/50726249-c856fd00-110a-11e9-8ace-e4c9c3d65299.png)
![2019-01-05 4](https://user-images.githubusercontent.com/46401054/50726250-c8ef9380-110a-11e9-8cc6-f8595c18461a.png)

Please help. I read the documentation, but I couldn't find the answer to my problem. I trust someone else has such a problem and knows the answer.
Does not work:
Edit profile -> Upload profile photo
Edit Ad -> Upload Photo
Does not work with the default theme or chameleon theme.
You have a host on HostPapa.com and Namecheap.com, but it doesn't work anywhere.
The website address is https://ad724.eu
Nothing happens by pressing the upload button, just updating the page. But he doesn't fill up the photo.
The other one redirects to / oc-panel / profile / image, but indicates a 403 error.
I'm trying to upload screenshots.
Thank you in advance for your help!

Peter Szabo

**Comment by neo22s** [comment]
Hello this is not the support center these are the docs.

**Comment by Aquilotiene** [comment]
Hello, I have the same mistake.

**Comment by neo22s** [comment]
Hello this is not the support center these are the docs.
